name: Quality (Prettier, ESLint, Dependency Graph, Jest, Build)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  quality:
    name: Quality (Prettier, ESLint, Dependency Graph, Build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
          scope: '@smartive-education'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run Prettier
        run: npm run format:check
      - name: Run ESLint
        run: npm run lint
      - name: Run Dependency Graph
        run: npm run dep-graph:validate
      - name: Run Jest/Test-Library Tests
        run: npm run test:ci
      - name: Run Build
        run: npm run build
        env:
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
          NEXT_PUBLIC_QWACKER_API_URL: ${{ secrets.NEXT_PUBLIC_QWACKER_API_URL }}
          ZITADEL_ISSUER: ${{ secrets.ZITADEL_ISSUER }}
          ZITADEL_CLIENT_ID: ${{ secrets.ZITADEL_CLIENT_ID }}
          REVALIDATE_SECRET_TOKEN: ${{ secrets.REVALIDATE_SECRET_TOKEN }}
