name: Build/Release Docker Image on Github Container Registry and run e2e tests
on:
  pull_request:
    branches:
      - main
jobs:
  publish:
    name: Build and Release Docker Image on Github Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.triggering_actor }}
          password: ${{ secrets.GITHUB_TOKEN   }}
      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL_PROD }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            ZITADEL_ISSUER=${{ secrets.ZITADEL_ISSUER }}
            ZITADEL_CLIENT_ID=${{ secrets.ZITADEL_CLIENT_ID }}
            REVALIDATE_SECRET_TOKEN=${{ secrets.REVALIDATE_SECRET_TOKEN }}
            NEXT_PUBLIC_QWACKER_API_URL=${{ secrets.NEXT_PUBLIC_QWACKER_API_URL }}
            NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL_PROD }}
            COMMIT_SHA={{ github.sha }},
            BUILD_VERSION=${{ github.sha }}
          secrets: |
            "npmrc=${{ secrets.NPMRC }}"
          push: true
          tags: |
            ghcr.io/smartive-education/app-team-ost:latest
            ghcr.io/smartive-education/app-team-ost:${{ github.sha }}
  test-e2e: 
    name: Playwright e2e tests
    runs-on: ubuntu-latest
    needs:
      - publish
    services:
      latest:
        image: ghcr.io/smartive-education/app-team-ost:latest
        env:
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          ZITADEL_ISSUER: ${{ secrets.ZITADEL_ISSUER }}
          ZITADEL_CLIENT_ID: ${{ secrets.ZITADEL_CLIENT_ID }}
          REVALIDATE_SECRET_TOKEN: ${{ secrets.REVALIDATE_SECRET_TOKEN }}
          NEXT_PUBLIC_QWACKER_API_URL: ${{ secrets.NEXT_PUBLIC_QWACKER_API_URL }}
          NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
          ZITADEL_USERNAME: ${{ secrets.ZITADEL_USERNAME }}
          ZITADEL_PASSWORD: ${{ secrets.ZITADEL_PASSWORD }}
        ports:
          - 3000:3000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
          scope: '@smartive-education'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test-playwright
        env:
          ZITADEL_USERNAME: ${{ secrets.ZITADEL_USERNAME }}
          ZITADEL_PASSWORD: ${{ secrets.ZITADEL_PASSWORD }}
          NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30